In [3]:
import pandas as pd
import numpy as np
import re
from tabulate import tabulate
import time 
import datetime

import matplotlib.pyplot as plt
import seaborn as sns
import nltk
from nltk.corpus import stopwords

from sklearn.feature_extraction.text import TfidfVectorizer, TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer

from sklearn.model_selection import cross_val_score

from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import *
from sklearn import *

import sklearn.externals
import joblib

from imblearn.over_sampling import SMOTE

import pickle

import sklearn.neighbors._base
import warnings
warnings.filterwarnings('ignore')

% matplotlib inline

In [4]:
from google.colab import drive 
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [5]:
## Reading the csv file
reviews = pd.read_csv("/content/gdrive/MyDrive/Capstone_Vidya/Capstone_Vidya/Capstone_Vidya/sample30.csv")

In [6]:
## Displaying the head
reviews.head()

id            brand  ... reviews_username user_sentiment
0  AV13O1A8GV-KLJ3akUyj  Universal Music  ...           joshua       Positive
1  AV14LG0R-jtxr-f38QfS         Lundberg  ...        dorothy w       Positive
2  AV14LG0R-jtxr-f38QfS         Lundberg  ...        dorothy w       Positive
3  AV16khLE-jtxr-f38VFn              K-Y  ...          rebecca       Negative
4  AV16khLE-jtxr-f38VFn              K-Y  ...        walker557       Negative

[5 rows x 15 columns]

# Data Cleansing and Pre-processing

In [7]:
## Checking the shape of the data frame
reviews.shape

(30000, 15)

In [8]:
## Checking the info of the data set
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   id                    30000 non-null  object
 1   brand                 30000 non-null  object
 2   categories            30000 non-null  object
 3   manufacturer          29859 non-null  object
 4   name                  30000 non-null  object
 5   reviews_date          29954 non-null  object
 6   reviews_didPurchase   15932 non-null  object
 7   reviews_doRecommend   27430 non-null  object
 8   reviews_rating        30000 non-null  int64 
 9   reviews_text          30000 non-null  object
 10  reviews_title         29810 non-null  object
 11  reviews_userCity      1929 non-null   object
 12  reviews_userProvince  170 non-null    object
 13  reviews_username      29937 non-null  object
 14  user_sentiment        29999 non-null  object
dtypes: int64(1), object(14)
memory usage

In [9]:
## Checking for the null value counts
reviews.isnull().sum()

id                          0
brand                       0
categories                  0
manufacturer              141
name                        0
reviews_date               46
reviews_didPurchase     14068
reviews_doRecommend      2570
reviews_rating              0
reviews_text                0
reviews_title             190
reviews_userCity        28071
reviews_userProvince    29830
reviews_username           63
user_sentiment              1
dtype: int64

In [10]:
## Checking the Null value count percentages
round(100*reviews.isnull().sum()/reviews.shape[0],2)

id                       0.00
brand                    0.00
categories               0.00
manufacturer             0.47
name                     0.00
reviews_date             0.15
reviews_didPurchase     46.89
reviews_doRecommend      8.57
reviews_rating           0.00
reviews_text             0.00
reviews_title            0.63
reviews_userCity        93.57
reviews_userProvince    99.43
reviews_username         0.21
user_sentiment           0.00
dtype: float64

In [11]:
## Dropping the columns reviews_userCity and reviews_userProvince as they have more than 90% null values and seems to be no importance for the analysis
reviews = reviews.drop(['reviews_userCity','reviews_userProvince'],axis=1)
reviews.shape

(30000, 13)

In [12]:
## checking again the null value percentages
round(100*reviews.isnull().sum()/reviews.shape[0],2)

id                      0.00
brand                   0.00
categories              0.00
manufacturer            0.47
name                    0.00
reviews_date            0.15
reviews_didPurchase    46.89
reviews_doRecommend     8.57
reviews_rating          0.00
reviews_text            0.00
reviews_title           0.63
reviews_username        0.21
user_sentiment          0.00
dtype: float64

In [13]:
## Displaying the head
reviews.head()

id            brand  ... reviews_username user_sentiment
0  AV13O1A8GV-KLJ3akUyj  Universal Music  ...           joshua       Positive
1  AV14LG0R-jtxr-f38QfS         Lundberg  ...        dorothy w       Positive
2  AV14LG0R-jtxr-f38QfS         Lundberg  ...        dorothy w       Positive
3  AV16khLE-jtxr-f38VFn              K-Y  ...          rebecca       Negative
4  AV16khLE-jtxr-f38VFn              K-Y  ...        walker557       Negative

[5 rows x 13 columns]

In [14]:
## Checking the user_sentiment which has null value
reviews[reviews['user_sentiment'].isnull()]

id   brand  ... reviews_username user_sentiment
28354  AVpfRTh1ilAPnD_xYic2  Disney  ...         7.87E+11            NaN

[1 rows x 13 columns]

## Imputing default values for the Null Values

In [15]:
## There are Null values in manufacturer column and we can impute the Brand values as Brand and Manufacturer seems to have similarity
reviews['manufacturer'] = np.where(reviews['manufacturer'].isnull(),reviews['brand'],reviews['manufacturer'])

## There is one record with user_sengtiment as Null and imputed manually with Positive based on the reviews_rating column.
reviews['user_sentiment'] = np.where(reviews['user_sentiment'].isnull(),'Positive',reviews['user_sentiment'])

## reviews_didPurchase and reviews_doRecommend has Null values and I will impute them with "N/A" 
reviews['reviews_didPurchase'] = reviews['reviews_didPurchase'].fillna('N/A')
reviews['reviews_doRecommend'] = reviews['reviews_doRecommend'].fillna('N/A')

## We could see there is null values for Reviews_date and can be imputed with default date.
reviews['reviews_date'] = reviews['reviews_date'].fillna('1969-12-31T00:00:00.000Z')

## There are some records with reviews_username as Null and i will impute with "Anonymus" user.
reviews['reviews_username'] = reviews['reviews_username'].fillna('Anonymus')

## Imputing Niull values in reviews_title with reviews_text as title also has similar text
reviews['reviews_title'] = np.where(reviews['reviews_title'].isnull(),reviews['reviews_text'],reviews['reviews_title'])



In [16]:
def is_date_matching(date_str):
    try:
        return datetime.datetime.strptime(date_str, '%Y-%m-%d')
    except ValueError:
        return datetime.datetime.strptime('1969-12-31', '%Y-%m-%d')

In [17]:
## Extracting date part alone as timestamp part is not required for our analysis
reviews['reviews_date'] = reviews['reviews_date'].apply(lambda x: x.split('T')[0])
## Cleaning date column with proper default date and creating reviews_year column for analysis
reviews['reviews_date'] = reviews['reviews_date'].apply(lambda x: is_date_matching(x))
reviews['reviews_year'] = reviews['reviews_date'].apply(lambda x: x.year)

In [18]:
## Checking for the transformed columns
reviews.head()

id            brand  ... user_sentiment reviews_year
0  AV13O1A8GV-KLJ3akUyj  Universal Music  ...       Positive         2012
1  AV14LG0R-jtxr-f38QfS         Lundberg  ...       Positive         2017
2  AV14LG0R-jtxr-f38QfS         Lundberg  ...       Positive         2017
3  AV16khLE-jtxr-f38VFn              K-Y  ...       Negative         2016
4  AV16khLE-jtxr-f38VFn              K-Y  ...       Negative         2016

[5 rows x 14 columns]

## Tranforming Target column

In [19]:
## Tranforming the user_sentiment from Categorical to Numeric as this is our prediction variable
reviews['user_sentiment'] = reviews['user_sentiment'].map({'Positive': 1, 'Negative': 0}).astype('int')

In [38]:
## Pre-processing the reviews_text
## Keeping only alphabets which are necessary for classification. Also convert the text to lower case
reviews['reviews_text'] = reviews['reviews_text'].apply(lambda x: re.sub('[^a-zA-Z]+', ' ', x.lower()).strip())

In [39]:
## Downloading required nltk libraries
nltk.download('wordnet')
nltk.download('punkt')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

### Lemmatization

In [40]:
## Tokenize and Applying Lemmatization to the review_text
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

wordnet_lemmatizer = WordNetLemmatizer()
reviews['reviews_text'] = reviews['reviews_text'].apply(lambda x: ' '.join([wordnet_lemmatizer.lemmatize(token, pos='n') for token in word_tokenize(x)]))


In [41]:
## Lets check again info of the data
reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype         
---  ------               --------------  -----         
 0   id                   30000 non-null  object        
 1   brand                30000 non-null  object        
 2   categories           30000 non-null  object        
 3   manufacturer         30000 non-null  object        
 4   name                 30000 non-null  object        
 5   reviews_date         30000 non-null  datetime64[ns]
 6   reviews_didPurchase  30000 non-null  object        
 7   reviews_doRecommend  30000 non-null  object        
 8   reviews_rating       30000 non-null  int64         
 9   reviews_text         30000 non-null  object        
 10  reviews_title        30000 non-null  object        
 11  reviews_username     30000 non-null  object        
 12  user_sentiment       30000 non-null  int64         
 13  reviews_year         30000 non-

# Model Building

In [42]:
## Assigning X,y,seed values for the model building 
seed = 42
X = reviews['reviews_text']
y = reviews['user_sentiment']

# Feature Extraction


In [43]:
## Getting the stowords from nltk for Text analysis
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


## TF-IDF

In [44]:
## Getting the features
tfidf_vec = TfidfVectorizer(
    max_features=None, 
    lowercase=True, 
    analyzer='word', 
    stop_words= stop_words, 
    ngram_range=(1, 1))


# Logistic Regression

In [45]:
# Checking class imbalnce is present or not
y.value_counts()

1    26633
0     3367
Name: user_sentiment, dtype: int64

## Above clearly shows there is imbalance in the sentiments. I will apply SMOTE technique to overcome that after splitting into Train and Test daat sets.

In [46]:
## Splitting the data to train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=seed)

## Applying TF-IDF to extract train, test feature set
tfidf_vec.fit(X_train)
X_train = tfidf_vec.transform(X_train)
X_test = tfidf_vec.transform(X_test)

## Applying SMOTE for imbalance data
sm = SMOTE()
X_train_smote, y_train_smote = sm.fit_sample(X_train, y_train)
X_test_smote, y_test_smote = sm.fit_sample(X_test, y_test)


In [47]:
## Logistic Regression
model = LogisticRegression(penalty="l2", random_state=seed, max_iter=500)

## Model fit
model.fit(X_train_smote, y_train_smote)

## Model Prediction
y_pred = model.predict(X_test_smote)

In [48]:
## Accuracy
train_accuracy = model.score(X_train_smote, y_train_smote)
test_accuracy = model.score(X_test_smote, y_test_smote)

## Classification report
model_performance = classification_report(y_test_smote, y_pred)

y_pred_proba = model.predict_proba(X_test_smote)
roc_auc = roc_auc_score(y_test_smote, y_pred_proba[:,1])


print('')
print(model_performance)
print('')

print ('Training Accuracy: ', round(train_accuracy,2))
print ('Testing Accuracy: ', round(test_accuracy,2))
print('ROC_AUC score: ', round(roc_auc,2))


              precision    recall  f1-score   support

           0       0.92      0.91      0.92      5349
           1       0.91      0.92      0.92      5349

    accuracy                           0.92     10698
   macro avg       0.92      0.92      0.92     10698
weighted avg       0.92      0.92      0.92     10698


Training Accuracy:  0.96
Testing Accuracy:  0.92
ROC_AUC score:  0.97


## Save the ML Model

In [49]:
# Save the model as a pickle in a file 
joblib.dump(model, '/content/gdrive/MyDrive/Capstone_Vidya/Capstone_Vidya/Capstone_Vidya/lr_model.pkl') 
# Save the TF-IDF model as a pickle in a file 
joblib.dump(tfidf_vec, '/content/gdrive/MyDrive/Capstone_Vidya/Capstone_Vidya/Capstone_Vidya/tfidf_model.pkl') 

['/content/gdrive/MyDrive/Capstone_Vidya/Capstone_Vidya/Capstone_Vidya/tfidf_model.pkl']

## Load the ML Model

In [50]:
# Load the model from the file 
lr_pickle_model = joblib.load('/content/gdrive/MyDrive/Capstone_Vidya/Capstone_Vidya/Capstone_Vidya/lr_model.pkl') 
# Load the model from the file 
tfidf_pickle_model = joblib.load('/content/gdrive/MyDrive/Capstone_Vidya/Capstone_Vidya/Capstone_Vidya/tfidf_model.pkl') 

In [51]:
# Use the loaded model to make predictions
response_lr_model = lr_pickle_model.predict(X_test)

## Evaluate the Loaded Model

In [52]:
# predict sentiment on test data
y_pred_load = lr_pickle_model.predict(X_test)

# create onfusion matrix
cm_load = confusion_matrix(y_test, y_pred_load)
print(cm_load)

#Checking the accuracy
print("Accuracy: \t",round(lr_pickle_model.score(X_test, y_test),2))

# check area under curve
y_pred_prob_load = lr_pickle_model.predict_proba(X_test)[:, 1]
print("ROC:    \t", round(roc_auc_score(y_test, y_pred_prob_load),2))

[[ 574   77]
 [ 434 4915]]
Accuracy: 	 0.91
ROC:    	 0.96


# Product Recommendation

### Now lets get the top 15 products from the Recommendation system.
### We are going to execute Item-based Recommendation system



### Dividing the dataset into train and test

In [53]:
## Taking the required columns - username,brand(product) and ratings from the data set
df_recommend = pd.DataFrame(data = reviews[['reviews_username','id','reviews_rating']])
## Checking the data set
df_recommend.head()

reviews_username                    id  reviews_rating
0           joshua  AV13O1A8GV-KLJ3akUyj               5
1        dorothy w  AV14LG0R-jtxr-f38QfS               5
2        dorothy w  AV14LG0R-jtxr-f38QfS               5
3          rebecca  AV16khLE-jtxr-f38VFn               1
4        walker557  AV16khLE-jtxr-f38VFn               1

In [54]:
## If there are any duplicate ratings present for user and product combination then lets apply mean and take the average rating
df_recommend = df_recommend.groupby(['reviews_username','id'],as_index=False).agg({'reviews_rating':pd.Series.mode,'reviews_rating':np.mean})

In [55]:
## Changing column names for better understanding and representation
df_recommend['username'] = df_recommend['reviews_username']
df_recommend['product'] = df_recommend['id']
df_recommend['rating'] = round(df_recommend['reviews_rating'],1)
## Dropping the old columns and checking the data
df_recommend = df_recommend.drop(['reviews_username','id','reviews_rating'],axis=1)
df_recommend.head()

username               product  rating
0    00dog3  AVpe6FfKilAPnD_xQmHi     4.0
1   00sab00  AVpe41TqilAPnD_xQH3d     1.0
2   00sab00  AVpe59io1cnluZ0-ZgDU     3.0
3  01impala  AVpfPaoqLJeJML435Xk9     3.0
4  02dakota  AVpfPaoqLJeJML435Xk9     5.0

In [56]:
## Splitting the data into train and test sets
train, test = train_test_split(df_recommend, test_size=0.2, random_state=seed)
## check the shape of the data sets
print(train.shape)
print(test.shape)

(22084, 3)
(5521, 3)


In [57]:
## Checking info of the data frame
df_recommend.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 27605 entries, 0 to 27604
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   username  27605 non-null  object 
 1   product   27605 non-null  object 
 2   rating    27605 non-null  float64
dtypes: float64(1), object(2)
memory usage: 862.7+ KB


In [58]:
# Apply pivot to see the user ratings for each product and give '0' wherever rating is not provided by the user
df_product_features = train.pivot(
    index='username',
    columns='product',
    values='rating'
).fillna(0)

In [59]:
## Checking the data set after pivoting the data frame
df_product_features.head()

product      AV13O1A8GV-KLJ3akUyj  ...  AVpfvieo1cnluZ0-qdnu
username                           ...                      
00dog3                        0.0  ...                   0.0
00sab00                       0.0  ...                   0.0
02dakota                      0.0  ...                   0.0
02deuce                       0.0  ...                   0.0
06stidriver                   0.0  ...                   0.0

[5 rows x 260 columns]

# Copy train and test dataset

### These dataset will be used for prediction and evaluation.


*   Dummy train will be used later for prediction of the products which has not been rated by the user. To ignore the products rated by the user, we will mark it as 0 during prediction. The products not rated by user is marked as 1 for prediction.
*   Dummy test will be used for evaluation. To evaluate, we will only make prediction on the products rated by the user. So, this is marked as 1. This is just opposite of dummy_train



In [60]:
## Taking the copy of train and test data sets
dummy_train = train.copy()
dummy_test = test.copy()

In [61]:
## Changing the rating value to '0' if the user provided rating
dummy_train['rating'] = dummy_train['rating'].apply(lambda x: 0 if x>=1 else 1)
## Changing the rating value to '1' if the user provided rating
dummy_test['rating'] = dummy_test['rating'].apply(lambda x: 1 if x>=1 else 0)

In [62]:
# The products not rated by user is marked as 1 for prediction. 
dummy_train = dummy_train.pivot(
    index='username',
    columns='product',
    values='rating'
).fillna(1)

# The products not rated by user is marked as 0 for evaluation. 
dummy_test = dummy_test.pivot(
    index='username',
    columns='product',
    values='rating'
).fillna(0)

In [63]:
## Lets check the train data set
dummy_train.head()

product      AV13O1A8GV-KLJ3akUyj  ...  AVpfvieo1cnluZ0-qdnu
username                           ...                      
00dog3                        1.0  ...                   1.0
00sab00                       1.0  ...                   1.0
02dakota                      1.0  ...                   1.0
02deuce                       1.0  ...                   1.0
06stidriver                   1.0  ...                   1.0

[5 rows x 260 columns]

In [64]:
## Lets check the test data set
dummy_test.head()

product    AV16khLE-jtxr-f38VFn  ...  AVpfvieo1cnluZ0-qdnu
username                         ...                      
01impala                    0.0  ...                   0.0
0325home                    0.0  ...                   0.0
1234                        0.0  ...                   0.0
123cat123                   0.0  ...                   0.0
123too                      0.0  ...                   0.0

[5 rows x 193 columns]

# Item Based Similarity

In [65]:
## Taking the transpose of the reviews matrix to normalize the rating around the mean for different product ID. 
## In the user based similarity, we had taken mean for each user intead of each product. 
product_features = train.pivot(
    index='username',
    columns='product',
    values='rating'
).T

product_features.head()

username              00dog3  00sab00  02dakota  ...  zxjki  zzdiane  zzz1127
product                                          ...                         
AV13O1A8GV-KLJ3akUyj     NaN      NaN       NaN  ...    NaN      NaN      NaN
AV14LG0R-jtxr-f38QfS     NaN      NaN       NaN  ...    NaN      NaN      NaN
AV16khLE-jtxr-f38VFn     NaN      NaN       NaN  ...    NaN      NaN      NaN
AV1YGDqsGV-KLJ3adc-O     NaN      NaN       NaN  ...    NaN      NaN      NaN
AV1YlENIglJLPUi8IHsX     NaN      NaN       NaN  ...    NaN      NaN      NaN

[5 rows x 20254 columns]

In [66]:
## Normalising the product rating for each product
mean = np.nanmean(product_features, axis=1)
df_subtracted = (product_features.T-mean).T

In [67]:
df_subtracted.head()

username              00dog3  00sab00  02dakota  ...  zxjki  zzdiane  zzz1127
product                                          ...                         
AV13O1A8GV-KLJ3akUyj     NaN      NaN       NaN  ...    NaN      NaN      NaN
AV14LG0R-jtxr-f38QfS     NaN      NaN       NaN  ...    NaN      NaN      NaN
AV16khLE-jtxr-f38VFn     NaN      NaN       NaN  ...    NaN      NaN      NaN
AV1YGDqsGV-KLJ3adc-O     NaN      NaN       NaN  ...    NaN      NaN      NaN
AV1YlENIglJLPUi8IHsX     NaN      NaN       NaN  ...    NaN      NaN      NaN

[5 rows x 20254 columns]

In [68]:
## Finding the cosine similarity. Note that since the data is normalised, both the cosine metric and correlation metric will give the same value. 
from sklearn.metrics.pairwise import pairwise_distances

# User Similarity Matrix
item_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
item_correlation[np.isnan(item_correlation)] = 0
print(item_correlation)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [69]:
## Filtering the correlation only for which the value is greater than 0. (Positively correlated)
item_correlation[item_correlation<0]=0
item_correlation

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

# Prediction

In [70]:
item_predicted_ratings = np.dot((product_features.fillna(0).T),item_correlation)
item_predicted_ratings

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.03458652,
        0.        ],
       [0.        , 0.        , 0.01153019, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.0029185 ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.0576442 ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.00583699]])

In [71]:
item_predicted_ratings.shape

(20254, 260)

In [72]:
dummy_train.shape

(20254, 260)

### Filtering the rating only for the products not rated by the user for recommendation

In [73]:
item_final_rating = np.multiply(item_predicted_ratings,dummy_train)
item_final_rating.head()

product      AV13O1A8GV-KLJ3akUyj  ...  AVpfvieo1cnluZ0-qdnu
username                           ...                      
00dog3                        0.0  ...              0.000000
00sab00                       0.0  ...              0.000000
02dakota                      0.0  ...              0.000000
02deuce                       0.0  ...              0.000000
06stidriver                   0.0  ...              0.007296

[5 rows x 260 columns]

## Top 15 prediction for the user -1

In [74]:
item_final_rating.iloc[1].sort_values(ascending=False)[0:15]

product
AVpfE7puilAPnD_xUcCW    0.120537
AVpfNc9cLJeJML434tza    0.042088
AVpf5ujMilAPnD_xkQVi    0.040216
AVpfoSS51cnluZ0-oVH9    0.039377
AVpfthSailAPnD_xg3ON    0.038316
AVpfv4TlilAPnD_xhjNS    0.034587
AVpe6FfKilAPnD_xQmHi    0.031271
AVpe6PCDLJeJML43yFQH    0.029658
AVpfOmKwLJeJML435GM7    0.025282
AVpfJcHuLJeJML433ZrY    0.023106
AVpf0thK1cnluZ0-r8vR    0.021604
AVpf7aUAilAPnD_xkqbP    0.018944
AVpf9_3MLJeJML43GvdB    0.018559
AVpe8gsILJeJML43y6Ed    0.017407
AVpe31o71cnluZ0-YrSD    0.016873
Name: 00sab00, dtype: float64

# Evaluation

### Here lets evaluate for the product which is already rated by the user insead of predicting it for the product not rated by the user. 

# Using Item similarity

In [75]:
test_product_features = test.pivot(
    index='username',
    columns='product',
    values='rating'
).T

mean = np.nanmean(test_product_features, axis=1)
test_df_subtracted = (test_product_features.T-mean).T

test_item_correlation = 1 - pairwise_distances(test_df_subtracted.fillna(0), metric='cosine')
test_item_correlation[np.isnan(test_item_correlation)] = 0
test_item_correlation[test_item_correlation<0]=0

In [76]:
test_item_correlation.shape

(193, 193)

In [77]:
test_product_features.shape

(193, 5355)

In [78]:
test_item_predicted_ratings = (np.dot(test_item_correlation, test_product_features.fillna(0))).T
test_item_final_rating = np.multiply(test_item_predicted_ratings,dummy_test)
test_item_final_rating.head()

product    AV16khLE-jtxr-f38VFn  ...  AVpfvieo1cnluZ0-qdnu
username                         ...                      
01impala                    0.0  ...                   0.0
0325home                    0.0  ...                   0.0
1234                        0.0  ...                   0.0
123cat123                   0.0  ...                   0.0
123too                      0.0  ...                   0.0

[5 rows x 193 columns]

In [79]:
test_ = test.pivot(
    index='username',
    columns='product',
    values='rating'
)

In [80]:
from sklearn.preprocessing import MinMaxScaler
from numpy import *

X  = test_item_final_rating.copy() 
X = X[X>0]

scaler = MinMaxScaler(feature_range=(1, 5))
print(scaler.fit(X))
y = (scaler.transform(X))


test_ = test.pivot(
    index='username',
    columns='product',
    values='rating'
)

# Finding total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(y))

MinMaxScaler(copy=True, feature_range=(1, 5))


# Finding RMSE

In [81]:
rmse = (sum(sum((test_ - y )**2))/total_non_nan)**0.5
print(rmse)

0.38860832588224853


In [131]:
## Checking the shape of the final recommendations
item_final_rating.shape

(20254, 260)

In [136]:
final_pred_df = pd.DataFrame()
for i in np.arange(0,20254):  
    ## Getting the top 15 products for each user
    df = item_final_rating.iloc[i].sort_values(ascending=False)[:15]

    ## Removing the products which dont have any weightage calculated
    product_id = np.array(df.index[df.values != 0])
    user_name = item_final_rating.iloc[i].name

    ##Creating and storing in data frame at user_name and product
    sorted_user_predictions = pd.DataFrame({'product_id':product_id,'user_name':user_name})
    sorted_user_predictions.assign(product_id=sorted_user_predictions.product_id.str.split(",")).explode("product_id")

    sorted_user_predictions.set_index('product_id')
    final_pred_df = final_pred_df.append(sorted_user_predictions)

## Saving the Recommendations in pickle file

In [160]:
# open a file, where you ant to store the data
file = open('/content/gdrive/MyDrive/Capstone_Vidya/Capstone_Vidya/Capstone_Vidya/product_recommend.pkl', 'wb')

# dump information to that file
pickle.dump(final_pred_df, file)

# close the file
file.close()



## Saving the user reviews as pickle file

In [163]:
prod_review_df = reviews[['id','name','reviews_text']]

# open a file, where you ant to store the data
file = open('/content/gdrive/MyDrive/Capstone_Vidya/Capstone_Vidya/Capstone_Vidya/reviews_text.pkl', 'wb')

# dump information to that file
pickle.dump(prod_review_df, file)

# close the file
file.close()

## Test the pickle file working or not for sample users

In [165]:
# open a file, where you stored the pickled data
file = open('/content/gdrive/MyDrive/Capstone_Vidya/Capstone_Vidya/Capstone_Vidya/product_recommend.pkl', 'rb')

# dump information to that file
product_data = pickle.load(file)

# close the file
file.close()

# open a file, where you stored the pickled data
file = open('/content/gdrive/MyDrive/Capstone_Vidya/Capstone_Vidya/Capstone_Vidya/reviews_text.pkl', 'rb')

# dump information to that file
reviews_data = pickle.load(file)

# close the file
file.close()


In [166]:
user_recom = product_data[product_data['user_name'] == '00dog3']
user_recom

product_id user_name
0   AVpfOmKwLJeJML435GM7    00dog3
1   AVpe5s3RLJeJML43x4eA    00dog3
2   AVpe8gsILJeJML43y6Ed    00dog3
3   AVpe59io1cnluZ0-ZgDU    00dog3
4   AVpfN6Z71cnluZ0-gZmO    00dog3
5   AVpe41TqilAPnD_xQH3d    00dog3
6   AVpfAgSp1cnluZ0-b2-K    00dog3
7   AVpfRTh1ilAPnD_xYic2    00dog3
8   AVpf63aJLJeJML43F__Q    00dog3
9   AVpfJP1C1cnluZ0-e3Xy    00dog3
10  AVpf3VOfilAPnD_xjpun    00dog3

In [168]:
## Getting the reviews for the products recomended for the user
df = reviews_data.join(user_recom.set_index('product_id'),on=['id'],how="inner")

In [169]:
## Checking the shape
df.shape

(14998, 4)

In [170]:
## Getting the reviews for predicting the sentiments
X_test_user = df['reviews_text']
X_test_user = tfidf_pickle_model.transform(X_test_user)
X_test_user.shape

(14998, 13726)

In [171]:
## Model prediction
y_pred_user = lr_pickle_model.predict(X_test_user)

In [172]:
## Predictions
y_pred_user

array([0, 0, 0, ..., 1, 1, 1])

In [174]:
## printing the shapes of input and ouput data
print(df.shape)
print(y_pred_user.shape)

(14998, 4)
(14998,)


In [175]:
## Merging input and output to get the final results
user_sentiment = pd.DataFrame(data=y_pred_user, columns=['user_sentiment'], 
                            index=df.index.copy())
fnl_result = pd.merge(df, user_sentiment, how ='left',left_index = True, right_index = True)

In [180]:
## Checking the shape
fnl_result.shape


(14998, 5)

In [203]:
## Getting the products based on top 5 most positively reviewd using mean
new_df = fnl_result.groupby('name')['user_sentiment'].mean()
lst = new_df.sort_values(ascending=False)[:5].reset_index()
lst.iloc[0]['name']

'My Big Fat Greek Wedding 2 (blu-Ray + Dvd + Digital)'